### ISSUE TITLE
toJSX does not have a default for `options.file`

### ISSUE THREAD

**Issue by RoachaelRoadmunk** [mdx-js/mdx#1153]
### Subject of the issue

After the most recent release, Storybook will not build and returns this error:

```
WARN ./src/components/Box/Box.stories.mdx
WARN Module build failed (from ./node_modules/@mdx-js/loader/index.js):
WARN TypeError: Cannot read property 'path' of undefined
WARN     at Function.toJSX (project/node_modules/@storybook/addon-docs/node_modules/@mdx-js/mdx/mdx-hast-to-jsx.js:124:30)
WARN     at extractExports (project/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:396:29)
WARN     at Compiler (project/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:454:14)
WARN     at Function.stringify (project/node_modules/unified/index.js:354:12)
WARN     at pipelineStringify (project/node_modules/unified/index.js:41:18)
WARN     at wrapped (project/node_modules/trough/wrap.js:25:19)
WARN     at next (project/node_modules/trough/index.js:57:24)
WARN     at done (project/node_modules/trough/wrap.js:55:16)
WARN     at done (project/node_modules/unified/index.js:35:7)
WARN     at done (project/node_modules/unified/index.js:314:11)
WARN     at next (project/node_modules/trough/index.js:59:14)
WARN     at done (project/node_modules/trough/wrap.js:55:16)
WARN     at then (project/node_modules/trough/wrap.js:62:5)
WARN     at wrapped (project/node_modules/trough/wrap.js:45:9)
WARN     at next (project/node_modules/trough/index.js:57:24)
WARN     at done (project/node_modules/trough/wrap.js:55:16)
WARN  @ ./src/components/Box sync nonrecursive ^\.\/(?:(?:Box\.stories\.mdx)$)$ ./Box.stories.mdx
WARN  @ ./.storybook/generated-entry.js
WARN  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/preview.js ./.storybook/generated-entry.js
```
**This might be Storybook's issue to solve**, but it also seems as if there isn't a defaulting occurring for `options.file` inside of `toJSX()` [here](https://github.com/mdx-js/mdx/pull/1126/commits/5b1dda336b57eacd6eecb19a22501f5b58e933fd#diff-b327bc77915c976f12c6d2efb717f068R124), which was introduced in #1126. 

### Your environment

*   **OS**: OSX 10.15.5 
*   **Packages**: `@storybook/addon-docs ^5.3.13`, `@storybook/react ^5.3.13`
*   **Env**: lerna + yarn

### Steps to reproduce

1. Have a `.stories.mdx` file in a storybook build
2. execute the `build-storybook` script that Storybook ships with

### Expected behaviour

Storybook builds

### Actual behaviour

Storybook fails building with the above error

**Comment by wooorm** [comment]
This sounds like a storybook problem to me? 🤔 maybe you'll have better luck asking those folks?

**Comment by RoachaelRoadmunk** [comment]
After some more investigation... I am more convinced it is actually related to the commit I referenced. 

In there, `filename: options.file.path` is added. When I modified the file (mdx-hast-to-jsx.js) locally to `filename: options.filepath` the error was resolved. 

I believe the wrong option is possibly being selected. `options.file` does not appear to be part of the `options` object that is passed.

**Comment by owenallenaz** [comment]
I am experiencing the exact same issue. When I update my package.json to add the following to my `package.json` `dependencies` object the issue goes away.

```
"@mdx-js/loader": "1.6.7",
"@mdx-js/mdx": "1.6.7",
"@mdx-js/react": "1.6.7",
```

 So I think it is definitely related to 1.6.8. Now it might be in the way that `@storybook/addon-docs` uses it.

**Comment by tylergaw** [comment]
I hit this same thing and same as @owenallenaz, if I force `1.6.7` the warning in the description goes away, and I'm able to view `mdx` stories in Storybook. Just in case anyone else is hitting this, to continue working I'm adding a `resolutions` block to my `package.json` to force the previous version.

```
"resolutions": {
    "@mdx-js/loader": "1.6.7",
    "@mdx-js/mdx": "1.6.7",
    "@mdx-js/react": "1.6.7",
    "@mdx-js/util": "1.6.7"
  }
```

**Comment by johno** [comment]
Ah, yeah we need to more gracefully handle `null` for file. I'll have a fix in a few, thanks for reporting!

**Comment by johno** [comment]
This should now be fixed in version `1.6.9`. Please let us know if that doesn't work. Thanks!

**Comment by dustinsavery** [comment]
@johno Issue still seems to be there, same error.
![image](https://user-images.githubusercontent.com/2447456/87731518-8850eb80-c77f-11ea-9023-e43cfeff079d.png)

Confirmed the upgrade to `1.6.9`

**Comment by johno** [comment]
Hrmmm. Bummer! Thanks for checking @dustinsavery 

Could someone perhaps provide a reproduction so I can debug this more deeply?

**Comment by johno** [comment]
I’m guessing the file argument must be coming in as null rather than undefined.

**Comment by dustinsavery** [comment]
It's called from [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/mdx/mdx-compiler-plugin.js#L314)

**Comment by dustinsavery** [comment]
@johno Could you conditionally add the filename property [here](https://github.com/mdx-js/mdx/blob/7d0cf97d703896f53d3f5c720f1ab365bd9304a7/packages/mdx/mdx-hast-to-jsx.js#L124) if one is given? Either that or perhaps doing some null/undefined checks or optional chaining to verify the property exists?

**Comment by johno** [comment]
> Either that or perhaps doing some null/undefined checks or optional chaining to verify the property exists?

We should definitely add that, but right now the MDX core package isn't transpiled and we support older versions of node that don't have optional changing.

I've opened up [another PR](https://github.com/mdx-js/mdx/pull/1155) which will hopefully address more falsy edge cases.

**Comment by johno** [comment]
Hopefully `1.6.10` addresses it now 😆.

**Comment by dustinsavery** [comment]
@johno It didn't 😭 I went ahead and tested it and got a fix. PR is [here](https://github.com/mdx-js/mdx/pull/1156)

**Comment by JounQin** [comment]
@johno `1.6.10` won't work because `toJSX` is called inside `storybook` [source](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/mdx/mdx-compiler-plugin.js#L314).

**Comment by RoachaelRoadmunk** [comment]
> @johno It didn't 😭 I went ahead and tested it and got a fix. PR is [here](https://github.com/mdx-js/mdx/pull/1156)

Yes!! This looks like it will be the solution for me as well!

**Comment by RoachaelRoadmunk** [comment]
> @johno `1.6.10` won't work because `toJSX` is called inside `storybook` [source](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/mdx/mdx-compiler-plugin.js?rgh-link-date=2020-07-17T04%3A03%3A09Z#L314).

@tylergaw's suggestion of adding the latest version to `resolutions` worked for my team as well to override storybook @JounQin, in case that helps you!

**Comment by filipesperandio** [comment]
I've added the `resolutions` to `1.6.10` and I still get issues in storybook

<img width="1615" alt="Screen Shot 2020-07-17 at 01 37 24" src="https://user-images.githubusercontent.com/316873/87749212-6d599800-c7ce-11ea-85dc-4195d987a913.png">

**Comment by filipesperandio** [comment]
Forcing resolution back to 1.6.6 fixes it

**Comment by JounQin** [comment]
@mdx-js/mergers A patch version need to be released.

**Comment by silvenon** [comment]
Released `1.6.11` 🚀

**Comment by johno** [comment]
The latest version should now fix it. Please let us know if that isn't the case. Thanks all!

**Comment by silvenon** [comment]
I just want to add that `toJSX` is (currently) **internal** API. We didn't document it and we don't test it as a plugin, we only test it implicitly through `mdx`.

**Comment by wooorm** [comment]
Yeah, want to second @silvenon. It’s an internal function that Storybook is depending on. So while the exception is now gone, Storybook should still provide a virtual file, and It’ll change again completely in [`next`](https://github.com/mdx-js/mdx/blob/next/packages/mdx/mdx-hast-to-jsx.js)!

**Comment by pvds** [comment]
@silvenon tested with Storybook 5.3.19 I can confirm version `1.6.11` fixed the issue.

**Comment by shilman** [comment]
Thanks so much for the fix. If it's fine by you, we'll make the fix on the Storybook side (along with any other breaking fixes needed) when MDX 2.0 drops. Really looking forward to that---you guys are doing amazing work!!!

**Comment by RoachaelRoadmunk** [comment]
> @silvenon tested with Storybook 5.3.19 I can confirm version `1.6.11` fixed the issue.

Same here! Thanks for your help everyone!

**Comment by ananrey** [comment]
Thanks @RoachaelRoadmunk for reporting this issue.
