### ISSUE TITLE
`metaString` not being omitted from `pre` element

### ISSUE THREAD

**Issue by peduarte** [mdx-js/mdx#304]
### Subject of the issue

It appears that a `metaString` prop is being forwarded to the DOM element when using a `pre`.

### Steps to reproduce

**clone**
```
git clone https://github.com/mdx-js/mdx.git
```

**change directory and install dependencies**
```
cd mdx/examples/create-react-app
npm install 
```

**edit markdown**
Add a code block to `hello.md`
```
    ```
        test
    ```
```

**run it**
```
npm start
```

Open the console tab in Inspector tools to see the warning.

### Expected behaviour

What should happen?

`metaString` prop should be omitted

### Actual behaviour

What happens instead?

`metaString` prop is being forwarded to the DOM element

![image](https://user-images.githubusercontent.com/372831/48071890-44000080-e1d3-11e8-94b1-35d00dc844c6.png)

![image](https://user-images.githubusercontent.com/372831/48071911-50845900-e1d3-11e8-8dcd-667cba87438e.png)

**Comment by silvenon** [comment]
This should be fixed in the latest version. Let me know if it's not.

**Comment by peduarte** [comment]
Can still reproduce following my steps, since the dependencies in the Examples folder haven't been upgraded.

I can confirm that after upgrading them it works 👍 

Created a PR for it too: https://github.com/mdx-js/mdx/pull/305

👊
